# https://github.com/TimonVS/pr-labeler-action
feature: ['feature/*', 'feat/*']
fix: 'fix/*'
change: 'change/*'
improve: 'improve/*'
chore: 'chore/*'
docs: 'docs/*'
refactor: 'refactor/*'
style: 'style/*'
test: 'test/*'
ci: 'ci/*'
perf: 'perf/*'
