"""init db

迁移 ID: b7f2a95c7cb6
父迁移:
创建时间: 2025-08-10 13:13:57.165001

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "b7f2a95c7cb6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("alisten",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alisten_alistenconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("server_url", sa.String(), nullable=False),
        sa.Column("house_id", sa.String(), nullable=False),
        sa.Column("house_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alisten_alistenconfig")),
        sa.UniqueConstraint("session_id"),
        info={"bind_key": "alisten"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alisten_alistenconfig")
    # ### end Alembic commands ###
