"""remove and rename tables

Revision ID: 6c3d023e73d4
Revises: 84cf08678c89
Create Date: 2023-09-15 13:50:08.244676

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c3d023e73d4"
down_revision = "84cf08678c89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("check_in_weightrecord")
    op.drop_table("check_in_fitnessrecord")
    op.drop_table("check_in_dietaryrecord")
    op.drop_table("check_in_bodyfatrecord")
    op.drop_table("check_in_user")

    op.rename_table("check_in_weightrecord_temp", "check_in_weightrecord")
    op.rename_table("check_in_fitnessrecord_temp", "check_in_fitnessrecord")
    op.rename_table("check_in_dietaryrecord_temp", "check_in_dietaryrecord")
    op.rename_table("check_in_bodyfatrecord_temp", "check_in_bodyfatrecord")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
