"""create_temp_table

Revision ID: 97641dfc009c
Revises:
Create Date: 2023-09-15 12:23:51.523677

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97641dfc009c"
down_revision = "2c9967b2a1cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_in_userinfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_weight", sa.Float(), nullable=True),
        sa.Column("target_body_fat", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in_userinfo")),
    )
    op.create_table(
        "check_in_bodyfatrecord_temp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("body_fat", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in_bodyfatrecord")),
    )
    op.create_table(
        "check_in_dietaryrecord_temp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in_dietaryrecord")),
    )
    op.create_table(
        "check_in_fitnessrecord_temp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in_fitnessrecord")),
    )
    op.create_table(
        "check_in_weightrecord_temp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in_weightrecord")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("check_in_weightrecord_temp")
    op.drop_table("check_in_fitnessrecord_temp")
    op.drop_table("check_in_dietaryrecord_temp")
    op.drop_table("check_in_bodyfatrecord_temp")
    op.drop_table("check_in_userinfo")
    # ### end Alembic commands ###
