"""migrate data

修订 ID: ab1ae87b93e7
父修订: 41333e58f5eb
创建时间: 2023-10-29 18:24:16.625405

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from nonebot import logger
from sqlalchemy import Connection
from sqlalchemy.ext.asyncio import AsyncConnection
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

revision: str = "ab1ae87b93e7"
down_revision: str | Sequence[str] | None = "41333e58f5eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _migrate_old_data(ds_conn: Connection):
    DsBase = automap_base()
    DsBase.prepare(autoload_with=ds_conn)
    DsUserInfo = DsBase.classes.check_in_userinfo
    DsFitnessRecord = DsBase.classes.check_in_fitnessrecord
    DsDietaryRecord = DsBase.classes.check_in_dietaryrecord
    DsWeightRecord = DsBase.classes.check_in_weightrecord
    DsBodyFatRecord = DsBase.classes.check_in_bodyfatrecord

    Base = automap_base()
    Base.prepare(autoload_with=op.get_bind())
    UserInfo = Base.classes.check_in_userinfo
    FitnessRecord = Base.classes.check_in_fitnessrecord
    DietaryRecord = Base.classes.check_in_dietaryrecord
    WeightRecord = Base.classes.check_in_weightrecord
    BodyFatRecord = Base.classes.check_in_bodyfatrecord

    ds_sessioin = Session(ds_conn)
    session = Session(op.get_bind())

    # 写入数据
    logger.info("check_in: 发现来自 datastore 的数据，正在迁移...")
    for ds_user_info in ds_sessioin.query(DsUserInfo).all():
        user = UserInfo(
            id=ds_user_info.id,
            user_id=ds_user_info.user_id,
            target_weight=ds_user_info.target_weight,
            target_body_fat=ds_user_info.target_body_fat,
        )
        session.add(user)
    for ds_fitness_record in ds_sessioin.query(DsFitnessRecord).all():
        fitness_record = FitnessRecord(
            id=ds_fitness_record.id,
            user_id=ds_fitness_record.user_id,
            time=ds_fitness_record.time,
            message=ds_fitness_record.message,
        )
        session.add(fitness_record)
    for ds_dietary_record in ds_sessioin.query(DsDietaryRecord).all():
        dietary_record = DietaryRecord(
            id=ds_dietary_record.id,
            user_id=ds_dietary_record.user_id,
            time=ds_dietary_record.time,
            healthy=ds_dietary_record.healthy,
        )
        session.add(dietary_record)
    for ds_weight_record in ds_sessioin.query(DsWeightRecord).all():
        weight_record = WeightRecord(
            id=ds_weight_record.id,
            user_id=ds_weight_record.user_id,
            time=ds_weight_record.time,
            weight=ds_weight_record.weight,
        )
        session.add(weight_record)
    for ds_body_fat_record in ds_sessioin.query(DsBodyFatRecord).all():
        body_fat_record = BodyFatRecord(
            id=ds_body_fat_record.id,
            user_id=ds_body_fat_record.user_id,
            time=ds_body_fat_record.time,
            body_fat=ds_body_fat_record.body_fat,
        )
        session.add(body_fat_record)

    session.commit()
    logger.info("check_in: 迁移完成")


async def data_migrate(conn: AsyncConnection):
    from nonebot_plugin_datastore.db import get_engine

    async with get_engine().connect() as ds_conn:
        await ds_conn.run_sync(_migrate_old_data)


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_async(data_migrate)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
