"""init llm quota config

修订 ID: 93dec07c1e84
父修订:
创建时间: 2026-05-13 12:24:11.925779

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "93dec07c1e84"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("llm_quota",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_quota_groupquotaconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("api_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_quota_groupquotaconfig")),
        sa.UniqueConstraint("session_id", name="unique_group_quota_config"),
        info={"bind_key": "llm_quota"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_quota_groupquotaconfig")
    # ### end Alembic commands ###
