"""init db

Revision ID: 619b9e5aa550
Revises:
Create Date: 2023-03-04 13:33:33.451227

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "619b9e5aa550"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ff14_fflogs_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("character_name", sa.String(), nullable=False),
        sa.Column("server_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "user_id", "character_name", "server_name", name="unique-user"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ff14_fflogs_user")
    # ### end Alembic commands ###
