"""add index

Revision ID: 9452fd434415
Revises: b035a626bcd1
Create Date: 2023-09-19 18:58:20.154619

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "9452fd434415"
down_revision = "b035a626bcd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ff14_fflogs_user_user_id"), ["user_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ff14_fflogs_user_user_id"))

    # ### end Alembic commands ###
