"""rename user to user_id

Revision ID: b035a626bcd1
Revises: 9149f07d54a1
Create Date: 2023-09-16 16:13:13.179247

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b035a626bcd1"
down_revision = "9149f07d54a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.alter_column("user", new_column_name="user_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.alter_column("user_id", new_column_name="user")

    # ### end Alembic commands ###
