"""alter user constraint

Revision ID: f62a8ea8c07f
Revises: 619b9e5aa550
Create Date: 2023-03-05 22:46:05.780439

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f62a8ea8c07f"
down_revision = "619b9e5aa550"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.drop_constraint("unique-user", type_="unique")
        batch_op.create_unique_constraint("unique-user", ["platform", "user_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.drop_constraint("unique-user", type_="unique")
        batch_op.create_unique_constraint(
            "unique-user", ["platform", "user_id", "character_name", "server_name"]
        )

    # ### end Alembic commands ###
