"""add user

Revision ID: fa09d8974213
Revises: f62a8ea8c07f
Create Date: 2023-09-16 15:32:25.532613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa09d8974213"
down_revision = "f62a8ea8c07f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user", sa.Integer(), nullable=True))
        batch_op.drop_constraint("unique-user", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_ff14_fflogs_user_user"), ["user"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ff14_fflogs_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ff14_fflogs_user_user"))
        batch_op.create_unique_constraint("unique-user", ["platform", "user_id"])
        batch_op.drop_column("user")

    # ### end Alembic commands ###
