"""migrate data

修订 ID: 3d228011e96b
父修订: 65a94a4a643b
创建时间: 2023-10-29 18:41:38.769018

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from nonebot import logger
from sqlalchemy import Connection
from sqlalchemy.ext.asyncio import AsyncConnection
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

revision: str = "3d228011e96b"
down_revision: str | Sequence[str] | None = "65a94a4a643b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _migrate_old_data(ds_conn: Connection):
    DsBase = automap_base()
    DsBase.prepare(autoload_with=ds_conn)
    DsMorningGreeting = DsBase.classes.morning_greeting_morninggreeting

    Base = automap_base()
    Base.prepare(autoload_with=op.get_bind())
    MorningGreeting = Base.classes.morning_greeting_morninggreeting

    ds_sessioin = Session(ds_conn)
    session = Session(op.get_bind())

    # 写入数据
    logger.info("morning_greeting: 发现来自 datastore 的数据，正在迁移...")
    for ds_morning_greeting in ds_sessioin.query(DsMorningGreeting).all():
        morning_greeting = MorningGreeting(
            id=ds_morning_greeting.id,
            target=ds_morning_greeting.target,
        )
        session.add(morning_greeting)

    session.commit()
    logger.info("morning_greeting: 迁移完成")


async def data_migrate(conn: AsyncConnection):
    from nonebot_plugin_datastore.db import get_engine

    async with get_engine().connect() as ds_conn:
        await ds_conn.run_sync(_migrate_old_data)


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_async(data_migrate)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
