"""add target

Revision ID: 82ec0729d48a
Revises: be302fc8c192
Create Date: 2023-09-19 10:40:56.523574

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "82ec0729d48a"
down_revision = "be302fc8c192"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "morning_greeting_morninggreeting", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "target",
                sa.JSON().with_variant(
                    postgresql.JSONB(astext_type=sa.Text()), "postgresql"
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "morning_greeting_morninggreeting", schema=None
    ) as batch_op:
        batch_op.drop_column("target")

    # ### end Alembic commands ###
