"""init db

Revision ID: be302fc8c192
Revises:
Create Date: 2023-03-05 12:07:52.273711

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be302fc8c192"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "morning_greeting_morninggreeting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("bot_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=True),
        sa.Column("guild_id", sa.String(), nullable=True),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform",
            "bot_id",
            "group_id",
            "guild_id",
            "channel_id",
            name="unique_morning_greeting",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("morning_greeting_morninggreeting")
    # ### end Alembic commands ###
