"""remove bot_id platform et al

Revision ID: e3ce6ed12f34
Revises: 09b1ff566d51
Create Date: 2023-09-19 10:47:16.362657

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3ce6ed12f34"
down_revision = "09b1ff566d51"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "morning_greeting_morninggreeting", schema=None
    ) as batch_op:
        batch_op.drop_constraint("unique_morning_greeting", type_="unique")
        batch_op.drop_column("bot_id")
        batch_op.drop_column("channel_id")
        batch_op.drop_column("guild_id")
        batch_op.drop_column("platform")
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "morning_greeting_morninggreeting", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("platform", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("guild_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("channel_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("bot_id", sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint(
            "unique_morning_greeting",
            ["platform", "bot_id", "group_id", "guild_id", "channel_id"],
        )

    # ### end Alembic commands ###
