"""init db

迁移 ID: d24f67b08af3
父迁移:
创建时间: 2025-07-28 22:43:34.940321

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "d24f67b08af3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("group_bind",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_bind_groupbind",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("bind_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_bind_groupbind")),
        info={"bind_key": "group_bind"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_bind_groupbind")
    # ### end Alembic commands ###
