"""add target

Revision ID: 169da32b92d8
Revises: 260e463af484
Create Date: 2023-09-19 10:40:40.462656

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "169da32b92d8"
down_revision = "260e463af484"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hello_hello", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "target",
                sa.JSON().with_variant(
                    postgresql.JSONB(astext_type=sa.Text()), "postgresql"
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hello_hello", schema=None) as batch_op:
        batch_op.drop_column("target")

    # ### end Alembic commands ###
