"""add bot_id

Revision ID: 371e102dcdb9
Revises: 5469ed61acff
Create Date: 2023-09-30 08:39:55.899833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "371e102dcdb9"
down_revision = "5469ed61acff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hello_hello", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bot_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hello_hello", schema=None) as batch_op:
        batch_op.drop_column("bot_id")

    # ### end Alembic commands ###
