"""migrate data

修订 ID: 5fc001a169eb
父修订: e2f882d2c91d
创建时间: 2023-10-29 18:39:38.457428

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from nonebot import logger
from sqlalchemy import Connection
from sqlalchemy.ext.asyncio import AsyncConnection
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

revision: str = "5fc001a169eb"
down_revision: str | Sequence[str] | None = "e2f882d2c91d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _migrate_old_data(ds_conn: Connection):
    DsBase = automap_base()
    DsBase.prepare(autoload_with=ds_conn)
    DsHello = DsBase.classes.hello_hello

    Base = automap_base()
    Base.prepare(autoload_with=op.get_bind())
    Hello = Base.classes.hello_hello

    ds_sessioin = Session(ds_conn)
    session = Session(op.get_bind())

    # 写入数据
    logger.info("hello: 发现来自 datastore 的数据，正在迁移...")
    for ds_hello in ds_sessioin.query(DsHello).all():
        hello = Hello(
            id=ds_hello.id,
            target=ds_hello.target,
            bot_id=ds_hello.bot_id,
        )
        session.add(hello)

    session.commit()
    logger.info("hello: 迁移完成")


async def data_migrate(conn: AsyncConnection):
    from nonebot_plugin_datastore.db import get_engine

    async with get_engine().connect() as ds_conn:
        await ds_conn.run_sync(_migrate_old_data)


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_async(data_migrate)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
