"""remove platform et al

Revision ID: 9dbb35122585
Revises: 92c2c4affdce
Create Date: 2023-09-19 10:47:35.111407

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9dbb35122585"
down_revision = "92c2c4affdce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hello_hello", schema=None) as batch_op:
        batch_op.drop_constraint("unique_hello", type_="unique")
        batch_op.drop_column("channel_id")
        batch_op.drop_column("guild_id")
        batch_op.drop_column("platform")
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hello_hello", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("platform", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("guild_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("channel_id", sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint(
            "unique_hello", ["platform", "group_id", "guild_id", "channel_id"]
        )

    # ### end Alembic commands ###
