"""init db

Revision ID: 5cb13347bece
Revises:
Create Date: 2023-09-12 17:07:22.228191

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5cb13347bece"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_bind",
        sa.Column("pid", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("aid", sa.Integer(), nullable=False),
        sa.Column("bid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aid"],
            ["user_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bid"],
            ["user_user.id"],
        ),
        sa.PrimaryKeyConstraint("pid", "platform"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_bind")
    op.drop_table("user_user")
    # ### end Alembic commands ###
