"""init llm config

迁移 ID: 0cc75f2d06b0
父迁移:
创建时间: 2026-08-02 22:29:42.360316

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "0cc75f2d06b0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("llm",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_groupllmconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("tts_model", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_groupllmconfig")),
        sa.UniqueConstraint("session_id", name="unique_group_llm_config"),
        info={"bind_key": "llm"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_groupllmconfig")
    # ### end Alembic commands ###
