"""add temp user_id and group_id

Revision ID: c2363e778e1c
Revises: bea1ddc601b8
Create Date: 2023-09-18 15:57:03.881790

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2363e778e1c"
down_revision = "bea1ddc601b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cyber_hospital_patient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("new_user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("new_group_id", sa.String(), nullable=True))

    with op.batch_alter_table("cyber_hospital_record", schema=None) as batch_op:
        batch_op.alter_column("patient_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cyber_hospital_record", schema=None) as batch_op:
        batch_op.alter_column("patient_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("cyber_hospital_patient", schema=None) as batch_op:
        batch_op.drop_column("new_group_id")
        batch_op.drop_column("new_user_id")

    # ### end Alembic commands ###
