"""remove and rename user_id and group_id

Revision ID: c9cd5d567291
Revises: 897193349979
Create Date: 2023-09-18 16:03:37.585076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9cd5d567291"
down_revision = "897193349979"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cyber_hospital_patient", schema=None) as batch_op:
        batch_op.drop_column("user_id")
        batch_op.drop_column("group_id")
        batch_op.alter_column("new_user_id", new_column_name="user_id")
        batch_op.alter_column("new_group_id", new_column_name="group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cyber_hospital_patient", schema=None) as batch_op:
        batch_op.alter_column("group_id", new_column_name="new_group_id")
        batch_op.alter_column("user_id", new_column_name="new_user_id")
        batch_op.add_column(sa.Column("group_id", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("user_id", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
