"""migrate_session_id

迁移 ID: 443969e6764c
父迁移: 6894055fff61
创建时间: 2025-08-09 11:04:26.866126

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
from nonebot import logger
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

if TYPE_CHECKING:
    from collections.abc import Sequence


revision: str = "443969e6764c"
down_revision: str | Sequence[str] | None = "6894055fff61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MAPPING = {
    "console": "Console",
    "discord": "Discord",
    "dodo": "DoDo",
    "feishu": "Feishu",
    "kaiheila": "Kaiheila",
    "qq": "QQClient",
    "qqguild": "QQAPI",
    "telegram": "Telegram",
    "unknown": "Unknown",
}


def get_session_id(platform: str, group_id: str, guild_id: str, channel_id: str) -> str | None:
    """生成会话 ID"""
    if platform == "qq":
        if group_id and group_id.isdigit():
            platform = "QQClient"
        else:
            platform = "QQAPI"
    else:
        platform = MAPPING.get(platform, "Unknown")

    if group_id:
        return f"{platform}_{group_id}"
    if guild_id and channel_id:
        return f"{platform}_{guild_id}_{channel_id}"


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    Base = automap_base()
    Base.prepare(autoload_with=op.get_bind())
    session = Session(op.get_bind())

    MessageRecord = Base.classes.repeat_messagerecord
    Enabled = Base.classes.repeat_enabled

    # 写入数据
    logger.info("repeat: 开始迁移 session_id...")
    for message_record in session.query(MessageRecord).all():
        session_id = get_session_id(
            message_record.platform, message_record.group_id, message_record.guild_id, message_record.channel_id
        )
        if session_id:
            message_record.session_id = session_id
    for enabled in session.query(Enabled).all():
        session_id = get_session_id(enabled.platform, enabled.group_id, enabled.guild_id, enabled.channel_id)
        if session_id:
            enabled.session_id = session_id

    session.commit()
    logger.info("repeat: 迁移完成")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
