"""add session_id

迁移 ID: 6894055fff61
父迁移: ee037c1bb715
创建时间: 2025-08-09 10:59:17.590621

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "6894055fff61"
down_revision: str | Sequence[str] | None = "ee037c1bb715"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repeat_enabled", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_id", sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f("unique_enabled"), type_="unique")
        batch_op.create_unique_constraint("unique_enabled", ["session_id"])

    with op.batch_alter_table("repeat_messagerecord", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_id", sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f("unique_record"), type_="unique")
        batch_op.create_unique_constraint("unique_record", ["date", "session_id", "user_id"])

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repeat_messagerecord", schema=None) as batch_op:
        batch_op.drop_constraint("unique_record", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_record"), ["date", "platform", "group_id", "guild_id", "channel_id", "user_id"]
        )
        batch_op.drop_column("session_id")

    with op.batch_alter_table("repeat_enabled", schema=None) as batch_op:
        batch_op.drop_constraint("unique_enabled", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_enabled"), ["platform", "group_id", "guild_id", "channel_id"]
        )
        batch_op.drop_column("session_id")

    # ### end Alembic commands ###
