"""remove_platform

迁移 ID: f2fc3b1e4d3d
父迁移: 443969e6764c
创建时间: 2025-08-09 11:15:22.051588

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "f2fc3b1e4d3d"
down_revision: str | Sequence[str] | None = "443969e6764c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repeat_enabled", schema=None) as batch_op:
        batch_op.alter_column("session_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("channel_id")
        batch_op.drop_column("group_id")
        batch_op.drop_column("platform")
        batch_op.drop_column("guild_id")

    with op.batch_alter_table("repeat_messagerecord", schema=None) as batch_op:
        batch_op.alter_column("session_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.Integer(), nullable=False)
        batch_op.drop_column("channel_id")
        batch_op.drop_column("group_id")
        batch_op.drop_column("platform")
        batch_op.drop_column("guild_id")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repeat_messagerecord", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("guild_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("platform", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("group_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("channel_id", sa.VARCHAR(), nullable=False))
        batch_op.alter_column("user_id", existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column("session_id", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("repeat_enabled", schema=None) as batch_op:
        batch_op.add_column(sa.Column("guild_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("platform", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("group_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("channel_id", sa.VARCHAR(), nullable=False))
        batch_op.alter_column("session_id", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
